import { DocumentReport } from '../api/types';

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function buildReportHtml(report: DocumentReport): string {
  const risk = report.riskAnalysis;
  const clauses = report.clauseAnalysis?.clauses || [];
  const flags = risk?.flags || [];
  const suggestions = risk?.suggestions || [];

  const clauseRows = clauses
    .map(
      (c) =>
        `<tr><td style="font-weight:600;color:#0B1220;padding:8px 12px 8px 0;vertical-align:top;">${escapeHtml(
          c.label,
        )}</td><td style="padding:8px 0;color:#374151;">${escapeHtml(c.value)}</td></tr>`,
    )
    .join('');

  const flagItems = flags
    .map(
      (f) =>
        `<li style="margin-bottom:10px;"><strong style="color:#0B1220;">${escapeHtml(
          f.title,
        )}</strong><br/><span style="color:#6B7280;font-size:13px;">${escapeHtml(f.detail)}</span></li>`,
    )
    .join('');

  const suggestionItems = suggestions
    .map((s) => `<li style="margin-bottom:8px;color:#374151;">${escapeHtml(s)}</li>`)
    .join('');

  return `
  <html>
    <head><meta charset="utf-8" /></head>
    <body style="font-family:-apple-system,Helvetica,Arial,sans-serif;padding:32px;color:#111827;">
      <div style="background:#0B1220;color:white;padding:24px;border-radius:16px;margin-bottom:24px;">
        <div style="font-size:12px;letter-spacing:0.5px;color:#B7C0D1;text-transform:uppercase;">Document Type</div>
        <div style="font-size:22px;font-weight:700;margin-top:4px;">${escapeHtml(
          report.documentType?.replace(/_/g, ' ') || 'Document',
        )}</div>
        ${
          risk
            ? `<div style="margin-top:16px;font-size:14px;color:#D4AF37;font-weight:700;">${risk.level} RISK &middot; ${risk.score}/100</div>`
            : ''
        }
      </div>

      <h2 style="font-size:16px;color:#0B1220;">Summary</h2>
      <p style="color:#374151;line-height:1.6;">${escapeHtml(report.summary?.summaryText || '')}</p>

      ${
        flagItems
          ? `<h2 style="font-size:16px;color:#0B1220;">Risk Flags</h2><ul style="padding-left:18px;">${flagItems}</ul>`
          : ''
      }

      ${
        clauseRows
          ? `<h2 style="font-size:16px;color:#0B1220;">Clause Cards</h2><table style="width:100%;border-collapse:collapse;">${clauseRows}</table>`
          : ''
      }

      ${
        suggestionItems
          ? `<h2 style="font-size:16px;color:#0B1220;">Before Signing, Ask</h2><ol style="padding-left:18px;">${suggestionItems}</ol>`
          : ''
      }

      <p style="margin-top:32px;color:#9CA3AF;font-size:11px;text-align:center;">
        This is an informational explanation, not professional legal advice. Consult a qualified lawyer for important decisions.
        <br/>Generated by LegalLens AI &middot; ${escapeHtml(report.fileName)}
      </p>
    </body>
  </html>`;
}
